### ISSUE TITLE
[BUG] Не сохраняется галерея 

### ISSUE THREAD

**Issue by AsanoSakura** [DareFox/SaveDTF-Compose#2]
Не загружается информация с подборками картинок (по типу этого поста - https://dtf.ru/s/weaboo/1168696-marin-kitagawa-pered-snom-vsem-dobroy-nochi-i-sladkih-snov).
На выходе получается такой файл.
![image](https://user-images.githubusercontent.com/104155139/164495052-d3f693c6-2f69-498b-a2bd-318c18139f17.png)

**Comment by AsanoSakura** [comment]
Так же с этого поста скачивается всего 10 фотографий
https://dtf.ru/s/weaboo/1169682-podborka-saber-alter-ostorozhno-nohorny

**Comment by DareFox** [comment]
Вижу, пока что программа не видит изображения из галерии. Постараюсь сейчас пофиксить эту проблему

**Comment by DareFox** [comment]
Пофикшено в **[1.0.4](https://github.com/DareFox/SaveDTF-Compose/releases/tag/1.0.4)**
